### ISSUE TITLE
Ensure context messages don't go to Sentry if analytics are disabled

### ISSUE THREAD

**Issue by jviotti** [resin-io-modules/resin-raven#7]
We avoid calling `sentry.captureException(error);` if the `shouldReport` passed option returns `false`, however are we sure that Sentry stops intercepting `stderr` and `stdout`, which I believe it uses to provide error context (e.g: so you can know which messages got printed before/after an exception)?

**Comment by lurch** [comment]
This has been fixed now, right?
(IIRC @jviotti double-checked this by using a network packet sniffer)

**Comment by jviotti** [comment]
Closing stale issues
